// src/app/[locale]/signage/schedules/page.tsx
'use client';

// IMPORTANT: This page now expects a global `graphqlClient` (e.g., from '@/lib/graphql-client')
// The previous more detailed page-local mock client has been replaced by a simpler placeholder.

import React, { useState, useEffect, useCallback } from 'react';
import CalendarView from '@/app/[locale]/signage/frontend/components/schedule/CalendarView';
import ScheduleEventModal, { GraphQLTargetType, RecurrenceType, MonthlyRecurrenceType } from '@/app/[locale]/signage/frontend/components/schedule/ScheduleEventModal'; // Import enums if modal exports them
import { Button } from '@/components/ui/button';
import { PlusCircleIcon, Loader2, AlertTriangleIcon } from 'lucide-react';
import { toast } from 'sonner';


// Assuming global graphqlClient import
// import graphqlClient from '@/lib/graphql-client';
const graphqlClient: any = {
    query: async (params: {queryName: string, variables: any}) => { console.warn(`graphqlClient.query for ${params.queryName} not implemented (Schedules). Backend not connected.`); return []; },
    mutate: async (params: {mutationName: string, input: any}) => { console.warn(`graphqlClient.mutate for ${params.mutationName} not implemented (Schedules). Backend not connected.`); return null; }
};

// Types (ensure these match actual GraphQL types from your schema)
// These might be imported from a central types file generated by graphql-codegen
interface GraphQLPlaylist { id: string; name: string; }
interface GraphQLDeviceOrGroup { id: string; name: string; type: GraphQLTargetType; }
interface GraphQLScheduledEventTargetInput { id: string; type: GraphQLTargetType; }
interface WeeklyRecurrenceConfig { days: string[]; }
interface MonthlyRecurrenceConfig { type: MonthlyRecurrenceType; dayOfMonth?: number; weekOrdinal?: string; dayOfWeek?: string; }
interface GraphQLScheduledEventInput {
  title?: string; playlistId: string; targetInputs: GraphQLScheduledEventTargetInput[];
  startTime: string; endTime: string; recurrenceType?: RecurrenceType; rrule?: string;
  weeklyConfig?: WeeklyRecurrenceConfig | null; monthlyConfig?: MonthlyRecurrenceConfig | null;
  organizationId: string; playlistName?: string; allDay?: boolean | null;
}
interface GraphQLScheduledEvent {
  id: string; organizationId: string; title?: string; playlistId: string; playlistName?: string;
  targets: { id: string; name: string; type: GraphQLTargetType }[];
  startTime: string; endTime: string; recurrenceType?: RecurrenceType; rrule?: string;
  weeklyConfig?: WeeklyRecurrenceConfig | null; monthlyConfig?: MonthlyRecurrenceConfig | null;
  allDay?: boolean; timezone?: string; exceptions?: any[]; createdAt: string; updatedAt: string;
}


export default function ScheduleManagementPage() {
  const [scheduledEvents, setScheduledEvents] = useState<GraphQLScheduledEvent[]>([]);
  const [isLoadingEvents, setIsLoadingEvents] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isEventModalOpen, setIsEventModalOpen] = useState(false);
  const [editingEvent, setEditingEvent] = useState<GraphQLScheduledEvent | null>(null);
  const [modalPlaylists, setModalPlaylists] = useState<GraphQLPlaylist[]>([]);
  const [modalDevicesAndGroups, setModalDevicesAndGroups] = useState<GraphQLDeviceOrGroup[]>([]);
  const [isLoadingModalData, setIsLoadingModalData] = useState(false);
  const organizationId = "org_placeholder_123";

  const fetchScheduledEvents = useCallback(async (currentViewDate?: Date) => {
    setIsLoadingEvents(true); setError(null);
    try {
      const today = currentViewDate || new Date();
      const startDate = new Date(today.getFullYear(), today.getMonth(), 1).toISOString();
      const endDate = new Date(today.getFullYear(), today.getMonth() + 1, 0, 23, 59, 59).toISOString();
      console.log("Attempting to fetch scheduled events via global graphqlClient.");
      const result = await graphqlClient.query({
        queryName: 'listScheduledEvents',
        variables: { organizationId, dateRangeStart: startDate, dateRangeEnd: endDate }
      });
      setScheduledEvents(result || []);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Unknown error fetching schedule.";
      setError(message); toast.error(`Failed to load schedule: ${message}`);
      setScheduledEvents([]);
    } finally { setIsLoadingEvents(false); }
  }, [organizationId]);

  const fetchModalDropdownData = useCallback(async () => {
    setIsLoadingModalData(true);
    try {
      console.log("Attempting to fetch modal dropdown data via global graphqlClient.");
      const [playlistsResult, targetsResult] = await Promise.all([
          graphqlClient.query({ queryName: 'listPlaylistsForScheduler', variables: { organizationId } }),
          graphqlClient.query({ queryName: 'listDeviceGroupsForScheduler', variables: { organizationId } })
      ]);
      setModalPlaylists(playlistsResult || []);
      setModalDevicesAndGroups(targetsResult || []);
    } catch (error) {
      toast.error("Failed to load data for scheduler modal.");
    } finally { setIsLoadingModalData(false); }
  }, [organizationId]);

  useEffect(() => { fetchScheduledEvents(); fetchModalDropdownData(); }, [fetchScheduledEvents, fetchModalDropdownData]);

  const handleOpenEventModalForNew = (date?: Date) => { setEditingEvent(null); setIsEventModalOpen(true); };
  const handleOpenEventModalForEdit = (event: GraphQLScheduledEvent) => { setEditingEvent(event); setIsEventModalOpen(true); };

  const handleSaveEvent = async (eventData: GraphQLScheduledEventInput) => {
    try {
      console.log("Attempting to save event via global graphqlClient.");
      // Ensure organizationId is part of the input for the mutation
      const inputWithOrg = { ...eventData, organizationId };
      await graphqlClient.mutate({
          mutationName: 'createScheduledEvent',
          input: inputWithOrg
      });
      toast.success("Schedule event saved (mocked).");
      fetchScheduledEvents(); setIsEventModalOpen(false); return true;
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Unknown error during save.";
      toast.error(`Failed to save event: ${msg}`); return false;
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div><h1 className="text-2xl font-semibold dark:text-white">Content Schedule</h1><p className="text-gray-500 dark:text-gray-400">Plan content plays.</p></div>
        <Button onClick={() => handleOpenEventModalForNew()} disabled={isLoadingModalData}><PlusCircleIcon className="mr-2 h-4 w-4" /> {isLoadingModalData ? "Loading..." : "Create Schedule Entry"}</Button>
      </div>
      {isLoadingEvents && (<div className="flex items-center justify-center h-64"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground"/><p className="ml-2 dark:text-gray-300">Loading...</p></div>)}
      {error && !isLoadingEvents && (<div className="p-4 bg-red-100 text-red-700 border rounded-md dark:bg-red-900/20 dark:text-red-300 dark:border-red-700"><AlertTriangleIcon className="h-5 w-5 inline mr-2"/>Error: {error}<Button variant="link" onClick={() => fetchScheduledEvents()} className="ml-2 text-red-700 dark:text-red-300">Retry</Button></div>)}
      {!isLoadingEvents && !error && (<CalendarView events={scheduledEvents} onEventClick={handleOpenEventModalForEdit} onDateClick={handleOpenEventModalForNew}/>)}
      {isEventModalOpen && (
        <ScheduleEventModal
            key={editingEvent?.id || 'new-event'} event={editingEvent}
            isOpen={isEventModalOpen} onOpenChange={setIsEventModalOpen}
            onSave={handleSaveEvent}
            playlists={modalPlaylists} devicesAndGroups={modalDevicesAndGroups}
            isLoadingData={isLoadingModalData}
        />
      )}
    </div>
  );
}
